### ISSUE TITLE
Improvement: transition shorthand parsing

### ISSUE THREAD

**Issue by yyx990803** [weexteam/weex-styler#9]
Currently the parser would throw an error at [this line](https://github.com/weexteam/weex-styler/blob/master/index.js#L87) if transition shorthand is used (because `realProp` is an empty string at that point):

``` css
.some-class {
  transition: opacity .5s ease;
}
```

It would be great if we can handle the shorthand and parse it according to the [formal syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/transition#Formal_syntax).
